<?php
/**
 * @file
 * Module file for Ferries
 */

/**
 * Implements hook_block_info().
 */
function ferries_block_info() {
    $blocks = array();
    $blocks['schedule_by_route'] = array(
        'info' => t('Ferries: Sailing schedule by route'),
    );
    $blocks['make_reservations'] = array(
        'info' => t('Ferries: Make reservations'),
    );
    $blocks['buy_tickets'] = array(
        'info' => t('Ferries: Buy tickets'),
    );
    $blocks['ferry_alerts'] = array(
        'info' => t('Ferries: Ferry alerts'),
    );
    $blocks['live_ferry_status'] = array(
        'info' => t('Ferries: Live ferry status'),
    );
    $blocks['navigation_links'] = array(
        'info' => t('Ferries: Navigation links'),
    );
    $blocks['get_to_know_your_ferries'] = array(
        'info' => t('Ferries: Get to know your ferries'),
    );

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ferries_block_view($delta = '') {
    $block = array();
    switch($delta) {
        case 'schedule_by_route':
            $block['subject'] = t('<none>');
            $block['content'] = drupal_get_form('schedule_by_route_form');
            break;
        case 'make_reservations':
            $block['subject'] = t('<none>');
            $block['content'] = drupal_get_form('make_reservations_form');
            break;
        case 'buy_tickets':
            $block['subject'] = t('<none>');
            $block['content'] = drupal_get_form('buy_tickets_form');
            break;
        case 'ferry_alerts':
            $block['subject'] =  t('<none>');
            $block['content'] = build_ferry_alerts();
            break;
        case 'live_ferry_status':
            $block['subject'] =  t('<none>');
            $block['content'] = build_live_ferry_status();
            break;
        case 'get_to_know_your_ferries':
            $block['subject'] = t('<none>');
            $block['content'] = build_get_to_know_your_ferries();
            break;
        case 'navigation_links':
            $block['subject'] =  t('<none>');
            $block['content'] = build_navigation_links();
            break;
    }

    return $block;
}

function schedule_by_route_form($form, &$form_state) {
    $routes = array(
        'ana-sj' => t('Anacortes / San Juan Islands'),
        'pt-key' => t('Port Townsend / Coupeville'),
        'muk-cl' => t('Mukilteo / Clinton'),
        'ed-king' => t('Edmonds / Kingston'),
        'pd-tal' => t('Pt Defiance / Tahlequah'),
        'sea-bi' => t('Seattle / Bainbridge Island Reduced Service'),
        'sea-br' => t('Seattle / Bremerton Reduced Service'),
        'f-v-s' => t('2-Boat Fauntleroy / Vashon'),
        'f-s' => t('2-Boat Fauntleroy / Southworth'),
        's-v' => t('2-Boat Southworth / Vashon'),
    );
    $form['#prefix'] = '<div class="action-box-shadow">';
    $form['#suffix'] = '</div>';
    $form['header'] = array(
        '#title' => t('Find your sailing schedule by route'),
        '#markup' => '<h2>Find your sailing schedule by route</h2>'
    );
    $form['#method'] = 'get';
    $form['#attributes']['name'] = 'schedule-by-route-form';
    $form['#attributes']['class'] = 'schedule-by-route';
    $form['#id'] = 'schedule-by-route';
    $form['#action'] = 'https://www.wsdot.com/ferries/schedule/scheduledetailbyroute.aspx';
    $form['route'] = array(
        '#type' => 'select',
        '#options' => $routes,
        '#required' => TRUE,
        '#empty_option' => t('Select Route'),
        '#attributes' => array('onchange' => 'this.form.submit();'),
    );
    
    return $form;
}

function make_reservations_form($form, &$form_state) {
    $form['#prefix'] = '<div class="action-box-shadow">';
    $form['#suffix'] = '</div>';
    $form['header'] = array(
        '#title' => t('Save a spot for your vehicle on some routes'),
        '#markup' => '<h2>Save a spot for your vehicle on some routes</h2>'
    );
    $form['#method'] = 'get';
    $form['#attributes']['name'] = 'make-reservations-form';
    $form['#attributes']['class'] = 'make-reservations';
    $form['#id'] = 'make-reservations';
    $form['#action'] = 'https://secureapps.wsdot.wa.gov/ferries/reservations/vehicle/default.aspx';
    $form['submit_button'] = array(
        '#type' => 'submit',
        '#value' => t('Make reservations'),
    );

    return $form;
}

function buy_tickets_form($form, &$form_state) {
    $form['#prefix'] = '<div class="action-box-shadow">';
    $form['#suffix'] = '</div>';
    $form['header'] = array(
        '#title' => t('Buy your tickets or passes online'),
        '#markup' => '<h2>Buy your tickets or passes online</h2>'
    );
    $form['#method'] = 'get';
    $form['#attributes']['name'] = 'buy-tickets-form';
    $form['#attributes']['class'] = 'buy-tickets';
    $form['#id'] = 'buy-tickets';
    $form['#action'] = 'https://www.wsdot.wa.gov/ferries/wave2go/';
    $form['submit_button'] = array(
        '#type' => 'submit',
        '#value' => t('Buy tickets'),
    );

    return $form;
}

function build_navigation_links() {
    $output = "<ul class='navigation-links'>";
    $output .= "<li><a href='#'>Tickets</a></li>";
    $output .= "<li><a href='#'>Schedules</a></li>";
    $output .= "<li><a href='#'>Ferries and Terminals</a></li>";
    $output .= "<li><a href='#'>Rider Information</a></li>";
    $output .= "<li><a href='#'>About Us</a></li>";
    $output .= "</ul>";

    return $output;
}

function build_live_ferry_status() {
    $output = "<div style='padding: 8px 13px 8px 13px;background-color: rgba(151,215,0,0.05);'>";
    $output .= "<h2 class='pane-title'>Live ferry status</h2>";
    $output .= "<ul class='info-box'>";
    $output .= "<li><a href='#'>Realtime ferry tracker</a></li>";
    $output .= "<li><a href='#'>Boarding status by terminal</a></li>";
    $output .= "</ul>";
    $output .="</div>";

    return $output;
}

function build_ferry_alerts() {
    $json = file_get_contents("http://localhost:8000/WSFRouteAlert.js");
    $alert = json_decode($json, true);
    $publishDate = $alert[0]["PublishDate"];
    $alertFullTitle = $alert[0]['AlertFullTitle'];

    $output = "<div style='padding: 8px 13px 8px 13px; background-color: rgba(255,106,19,0.05);'>";
    $output .= "<h2 class='pane-title'>Ferry alerts</h2>";
    $output .= "<div>" . $publishDate . "</div>";
    $output .= "<div style='font-size: 1.125rem; font-weight: bold; padding: .75rem 0 1rem 0;'>" . $alertFullTitle . "</div>";
    $output .= "<ul class='info-box'>";
    $output .= "<li><a href='#'>All alerts</a></li>";
    $output .= "</ul>";
    $output .="</div>";

    return $output;
}

function build_get_to_know_your_ferries() {
    $output = "<div style='padding: 35px 13px 8px 13px;'>";
    $output .= "<h2 class='pane-title'>Get to know your ferries</h2>";
    $output .= "<div style='font-size: 1.25rem; font-weight: bold;'>All are welcome on Washington State Ferries</div>";
    $output .= "<p style='margin: 8px 0 24px 0;'>Here are some helpful tips on how to navigate the ferries.</p>";
    $output .= "<ul class='info-box'>";
    $output .= "<li><a href='#'>First time rider's guide</a></li>";
    $output .= "<li><a href='#'>Disabilities and medical assistance</a></li>";
    $output .= "<li><a href='#'>Route map</a></li>";
    $output .= "<li><a href='#'>Travel to Canada</a></li>";
    $output .= "<li><a href='#'>Contact Ferries</a></li>";
    $output .= "</ul>";
    $output .="</div>";

    return $output;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Need to don't see the parameters 'form_build_id' and 'form_id' in the url.
 */
function ferries_form_schedule_by_route_form_alter(&$form, &$form_state, $form_id) {
    unset($form['form_build_id'], $form['form_token'], $form['form_id']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Need to don't see the parameters 'form_build_id' and 'form_id' in the url.
 */
function ferries_form_make_reservations_form_alter(&$form, &$form_state, $form_id) {
    unset($form['form_build_id'], $form['form_token'], $form['form_id']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Need to don't see the parameters 'form_build_id' and 'form_id' in the url.
 */
function ferries_form_buy_tickets_form_alter(&$form, &$form_state, $form_id) {
    unset($form['form_build_id'], $form['form_token'], $form['form_id']);
}
