<?php
// L3 landing page functions exist in inc files
module_load_include('inc', 'ferries', 'ferries_l3_tickets');
module_load_include('inc', 'ferries', 'ferries_l3_schedules');
module_load_include('inc', 'ferries', 'ferries_l3_terminals');
module_load_include('inc', 'ferries', 'ferries_l3_rider_information');
module_load_include('inc', 'ferries', 'ferries_l3_footer');

/**
 * Implements hook_block_info().
 */
function ferries_block_info() {
    $blocks = array();
    // Homepage
    $blocks['select_route'] = array(
        'info' => t('Ferries: Select route'),
        'cache' => DRUPAL_NO_CACHE,
    );
    $blocks['make_reservations'] = array(
        'info' => t('Ferries: Make reservations'),
    );
    $blocks['buy_tickets'] = array(
        'info' => t('Ferries: Buy tickets'),
    );
    $blocks['ferry_alerts'] = array(
        'info' => t('Ferries: Ferry alerts'),
        'cache' => DRUPAL_NO_CACHE,
    );
    $blocks['rider_updates_highlight'] = array(
        'info' => t('Ferries: Rider updates'),
    );
    $blocks['live_ferry_status'] = array(
        'info' => t('Ferries: Live ferry status'),
    );
    $blocks['navigation_links'] = array(
        'info' => t('Ferries: Navigation links'),
    );
    $blocks['get_to_know_your_ferries'] = array(
        'info' => t('Ferries: Get to know your ferries'),
    );
    // Tickets
    $blocks['online_tickets'] = array(
        'info' => t('Ferries: Tickets: Online tickets'),
    );
    $blocks['ticket_information'] = array(
        'info' => t('Ferries: Tickets: Ticket information'),
    );
    $blocks['calculate_fares'] = array(
        'info' => t('Ferries: Tickets: Calculate fares'),
    );
    $blocks['vehicle_reservations'] = array(
        'info' => t('Ferries: Tickets: Vehicle reservations'),
    );
    $blocks['passes'] = array(
        'info' => t('Ferries: Tickets: Passes'),
    );
    $blocks['refunds'] = array(
        'info' => t('Ferries: Tickets: Refunds'),
    );
    // Schedules
    $blocks['schedule_by_route'] = array(
        'info' => t('Ferries: Schedules: Schedule by route'),
    );
    $blocks['schedule_by_date'] = array(
        'info' => t('Ferries: Schedules: Schedule by date'),
    );
    $blocks['low_tide_warning'] = array(
        'info' => t('Ferries: Schedules: Low tide warning'),
    );
    // Ferries and Terminals
    $blocks['travel_alerts'] = array(
        'info' => t('Ferries: Terminals: Travel alerts'),
    );
    $blocks['realtime_map'] = array(
        'info' => t('Ferries: Terminals: Realtime map'),
    );
    $blocks['terminal_cameras'] = array(
        'info' => t('Ferries: Terminals: Loading cameras by terminal'),
    );
    $blocks['other_ferry_systems'] = array(
        'info' => t('Ferries: Terminals: Other ferry systems'),
    );
    $blocks['about_our_fleet'] = array(
        'info' => t('Ferries: Terminals: About our fleet'),
    );
    // Rider Information
    $blocks['first_time_riders'] = array(
        'info' => t('Ferries: Rider Information: First time riders'),
    );
    $blocks['rider_updates'] = array(
        'info' => t('Ferries: Rider Information: Rider updates'),
    );
    $blocks['commercial_vehicles'] = array(
        'info' => t('Ferries: Rider Information: Commercial and oversized vehicles'),
    );
    $blocks['disabilities_medical'] = array(
        'info' => t('Ferries: Rider Information: Disabilities and medical assistance'),
    );
    $blocks['safety_security'] = array(
        'info' => t('Ferries: Rider Information: Safety and security'),
    );
    $blocks['travel_canada'] = array(
        'info' => t('Ferries: Rider Information: Travel to Canada'),
    );
    $blocks['groups_events'] = array(
        'info' => t('Ferries: Rider Information: Groups and events'),
    );
    $blocks['bring_onboard'] = array(
        'info' => t('Ferries: Rider Information: What you can bring onboard'),
    );
    // L3 footer
    $blocks['wsf_blog'] = array(
        'info' => t('Ferries: L3 Footer: WSF Blog'),
    );
    $blocks['news_stories'] = array(
        'info' => t('Ferries: L3 Footer: News stories'),
    );
    $blocks['twitter'] = array(
        'info' => t('Ferries: L3 Footer: Twitter'),
    );

    return $blocks;
}

 /**
 * Implements hook_block_view().
 */
function ferries_block_view($delta = '') {
    $block = array();
    switch($delta) {
        // Homepage
        case 'select_route':
            $block['subject'] = t('<none>');
            $block['content'] = drupal_get_form('select_route_form');
            break;
        case 'make_reservations':
            $block['subject'] = t('<none>');
            $block['content'] = drupal_get_form('make_reservations_form');
            break;
        case 'buy_tickets':
            $block['subject'] = t('<none>');
            $block['content'] = drupal_get_form('buy_tickets_form');
            break;
        case 'ferry_alerts':
            $block['subject'] =  t('<none>');
            $block['content'] = build_ferry_alerts();
            break;
        case 'rider_updates_highlight':
            $block['subject'] =  t('<none>');
            $block['content'] = build_rider_updates_highlight();
            break;
        case 'live_ferry_status':
            $block['subject'] =  t('<none>');
            $block['content'] = build_live_ferry_status();
            break;
        case 'navigation_links':
            $block['subject'] =  t('<none>');
            $block['content'] = build_navigation_links();
            break;
        case 'get_to_know_your_ferries':
            $block['subject'] = t('<none>');
            $block['content'] = build_get_to_know_your_ferries();
            break;
        // Tickets
        case 'online_tickets':
            $block['subject'] = t('<none>');
            $block['content'] = build_online_tickets();
            break;
        case 'ticket_information':
            $block['subject'] = t('<none>');
            $block['content'] = build_ticket_information();
            break;
        case 'calculate_fares':
            $block['subject'] = t('<none>');
            $block['content'] = build_calculate_fares();
            break;
        case 'vehicle_reservations':
            $block['subject'] = t('<none>');
            $block['content'] = build_vehicle_reservations();
            break;
        case 'passes':
            $block['subject'] = t('<none>');
            $block['content'] = build_passes();
            break;
        case 'refunds':
            $block['subject'] = t('<none>');
            $block['content'] = build_refunds();
            break;
        // Schedules
        case 'schedule_by_route':
            $block['subject'] = t('<none>');
            $block['content'] = build_schedule_by_route();
            break;
        case 'schedule_by_date':
            $block['subject'] = t('<none>');
            $block['content'] = build_schedule_by_date();
            break;
        case 'low_tide_warning':
            $block['subject'] = t('<none>');
            $block['content'] = build_low_tide_warning();
            break;
        // Ferries and Terminals
        case 'travel_alerts':
            $block['subject'] = t('<none>');
            $block['content'] = build_travel_alerts();
            break;
        case 'realtime_map':
            $block['subject'] = t('<none>');
            $block['content'] = build_realtime_map();
            break;
        case 'terminal_cameras':
            $block['subject'] = t('<none>');
            $block['content'] = build_terminal_cameras();
            break;
        case 'other_ferry_systems':
            $block['subject'] = t('<none>');
            $block['content'] = build_other_ferry_systems();
            break;
        case 'about_our_fleet':
            $block['subject'] = t('<none>');
            $block['content'] = build_about_our_fleet();
            break;
        // Rider Information
        case 'first_time_riders':
            $block['subject'] = t('<none>');
            $block['content'] = build_first_time_riders();
            break;
        case 'rider_updates':
            $block['subject'] = t('<none>');
            $block['content'] = build_rider_updates();
            break;
        case 'commercial_vehicles':
            $block['subject'] = t('<none>');
            $block['content'] = build_commercial_vehicles();
            break;
        case 'disabilities_medical':
            $block['subject'] = t('<none>');
            $block['content'] = build_disabilities_medical();
            break;
        case 'safety_security':
            $block['subject'] = t('<none>');
            $block['content'] = build_safety_security();
            break;
        case 'travel_canada':
            $block['subject'] = t('<none>');
            $block['content'] = build_travel_canada();
            break;
        case 'groups_events':
            $block['subject'] = t('<none>');
            $block['content'] = build_groups_events();
            break;
        case 'bring_onboard':
            $block['subject'] = t('<none>');
            $block['content'] = build_bring_onboard();
            break;
        // L3 footer
        case 'wsf_blog':
            $block['subject'] = t('<none>');
            $block['content'] = build_wsf_blog();
            break;
        case 'news_stories':
            $block['subject'] = t('<none>');
            $block['content'] = build_news_stories();
            break;
        case 'twitter':
            $block['subject'] = t('<none>');
            $block['content'] = build_twitter();
            break;
    }

    return $block;
}

/* Beginning of home page tiles */
function select_route_form($form, &$form_state) {
    $routes = array();
    $json = file_get_contents("https://data.wsdot.wa.gov/ferries/WSFScheduledRoutes.js");
    $scheduledRoutes = json_decode($json, true);

    foreach ($scheduledRoutes as $route) {
        $routes[$route['RouteAbbrev']] = $route['Description'];
    }

    $form['#prefix'] = '<div class="action-box-shadow">';
    $form['#suffix'] = '</div>';
    $form['header'] = array(
        '#title' => t('Find your sailing schedule by route'),
        '#markup' => '<h2>Find your sailing schedule by route</h2>'
    );
    $form['#method'] = 'get';
    $form['#attributes']['name'] = 'schedule-by-route-form';
    $form['#attributes']['class'] = 'schedule-by-route';
    $form['#id'] = 'schedule-by-route';
    $form['#action'] = 'https://www.wsdot.com/ferries/schedule/scheduledetailbyroute.aspx';
    $form['route'] = array(
        '#type' => 'select',
        '#options' => $routes,
        '#required' => TRUE,
        '#empty_option' => t('Select Route'),
        '#attributes' => array('onchange' => 'this.form.submit();'),
    );
    
    return $form;
}

function make_reservations_form($form, &$form_state) {
    $form['#prefix'] = '<div class="action-box-shadow">';
    $form['#suffix'] = '</div>';
    $form['header'] = array(
        '#title' => t('Save a spot for your vehicle on some routes'),
        '#markup' => '<h2>Save a spot for your vehicle on some routes</h2>'
    );
    $form['#method'] = 'get';
    $form['#attributes']['name'] = 'make-reservations-form';
    $form['#attributes']['class'] = 'make-reservations';
    $form['#id'] = 'make-reservations';
    $form['#action'] = 'https://secureapps.wsdot.wa.gov/ferries/reservations/vehicle/default.aspx';
    $form['submit_button'] = array(
        '#type' => 'submit',
        '#value' => t('Make reservations'),
    );

    return $form;
}

function buy_tickets_form($form, &$form_state) {
    $form['#prefix'] = '<div class="action-box-shadow">';
    $form['#suffix'] = '</div>';
    $form['header'] = array(
        '#title' => t('Buy your tickets or passes online'),
        '#markup' => '<h2>Buy your tickets or passes online</h2>'
    );
    $form['#method'] = 'get';
    $form['#attributes']['name'] = 'buy-tickets-form';
    $form['#attributes']['class'] = 'buy-tickets';
    $form['#id'] = 'buy-tickets';
    $form['#action'] = 'https://wave2go.wsdot.com/webstore/landingPage?cg=21&c=76';
    $form['submit_button'] = array(
        '#type' => 'submit',
        '#value' => t('Buy tickets'),
    );

    return $form;
}

function build_ferry_alerts() {
    $json = file_get_contents("https://data.wsdot.wa.gov/ferries/WSFRouteAlert.js");
    $alert = json_decode($json, true);
    $publishDate = $alert[0]["PublishDate"];
    $alertFullTitle = $alert[0]['AlertFullTitle'];

    $output = "<div style='padding: 8px 13px 8px 13px; background-color: rgba(255,106,19,0.05);'>";
    $output .= "<h2 class='pane-title'>Ferry alerts</h2>";
    $output .= "<div>" . $publishDate . "</div>";
    $output .= "<div style='font-size: 1.125rem; font-weight: bold; padding: .75rem 0 1.5rem 0;'>" . $alertFullTitle . "</div>";
    $output .= "<ul class='info-box'>";
    $output .= "<li><a href='https://www.wsdot.wa.gov/ferries/schedule/bulletin.aspx'>All alerts</a></li>";
    $output .= "</ul>";
    $output .= "</div>";

    return $output;
}

function build_rider_updates_highlight() {
    $output = "<div style='padding: 8px 13px 8px 13px;'>";
    $output .= "<h2 class='pane-title'>Rider updates</h2>";
    $output .= "<div style='padding-bottom: 1.5rem;'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <a href='#'>Praesent aliquet pulvinar quam ac bibendum.</a></div>";
    $output .= "<ul class='info-box'>";
    $output .= "<li><a href='/ferries/rider-information/updates'>All rider updates</a></li>";
    $output .= "</ul>";
    $output .= "</div>";

    return $output;
}

function build_live_ferry_status() {
    $output = "<div style='padding: 8px 13px 8px 13px;background-color: rgba(151,215,0,0.05);'>";
    $output .= "<h2 class='pane-title'>Live ferry status</h2>";
    $output .= "<ul class='info-box'>";
    $output .= "<li><a href='https://www.wsdot.com/ferries/vesselwatch/'>Realtime ferry tracker</a></li>";
    $output .= "<li><a href='https://www.wsdot.wa.gov/ferries/vesselwatch/terminals.aspx'>Boarding status by terminal</a></li>";
    $output .= "</ul>";
    $output .="</div>";

    return $output;
}

function build_navigation_links() {
    $output = "<ul class='navigation-links'>";
    $output .= "<li><a href='/ferries/tickets'>Tickets</a></li>";
    $output .= "<li><a href='/ferries/schedules'>Schedules</a></li>";
    $output .= "<li><a href='/ferries/terminals'>Ferries and Terminals</a></li>";
    $output .= "<li><a href='/ferries/rider-information'>Rider Information</a></li>";
    $output .= "<li><a href='/ferries/about-us'>About Us</a></li>";
    $output .= "</ul>";

    return $output;
}

function build_get_to_know_your_ferries() {
    $output = "<div style='padding: 35px 13px 8px 13px;'>";
    $output .= "<h2 class='pane-title'>Get to know your ferries</h2>";
    $output .= "<div style='font-size: 1.25rem; font-weight: bold;'>All are welcome on Washington State Ferries</div>";
    $output .= "<p style='margin: 8px 0 24px 0;'>Here are some helpful tips on how to navigate the ferries.</p>";
    $output .= "<ul class='info-box'>";
    $output .= "<li><a href='/ferries/rider-information/first-time'>First time rider's guide</a></li>";
    $output .= "<li><a href='/ferries/rider-information/ada'>Disabilities and medical assistance</a></li>";
    $output .= "<li><a href='/ferries/rider-information/route-map'>Route map</a></li>";
    $output .= "<li><a href='/ferries/rider-information/canada'>Travel to Canada</a></li>";
    $output .= "<li><a href='/ferries/about-us/contact'>Contact Ferries</a></li>";
    $output .= "</ul>";
    $output .= "</div>";

    return $output;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Need to don't see the parameters 'form_build_id' and 'form_id' in the url.
 */
function ferries_form_schedule_by_route_form_alter(&$form, &$form_state, $form_id) {
    unset($form['form_build_id'], $form['form_token'], $form['form_id']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Need to don't see the parameters 'form_build_id' and 'form_id' in the url.
 */
function ferries_form_make_reservations_form_alter(&$form, &$form_state, $form_id) {
    unset($form['form_build_id'], $form['form_token'], $form['form_id']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Need to don't see the parameters 'form_build_id' and 'form_id' in the url.
 */
function ferries_form_buy_tickets_form_alter(&$form, &$form_state, $form_id) {
    unset($form['form_build_id'], $form['form_token'], $form['form_id']);
}
